# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Urlencode < Formula
  desc ""
  homepage ""
  version "0.0.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dev-shimada/urlencode/releases/download/v0.0.3/urlencode_Darwin_x86_64.tar.gz"
      sha256 "cd7b462eb9d2449826f73f169137455a7eb7d0118791b9da1b67c233d68179a7"

      def install
        bin.install "urlencode"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dev-shimada/urlencode/releases/download/v0.0.3/urlencode_Darwin_arm64.tar.gz"
      sha256 "83196399f5129d68cef9de081370d97be5ebdf3c41e17abc18e2c8c02b73b5ae"

      def install
        bin.install "urlencode"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dev-shimada/urlencode/releases/download/v0.0.3/urlencode_Linux_x86_64.tar.gz"
        sha256 "faf960278fb9357425b58da2e8f2dc985efe35401b15569b1a3bee9401a020ed"

        def install
          bin.install "urlencode"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/dev-shimada/urlencode/releases/download/v0.0.3/urlencode_Linux_arm64.tar.gz"
        sha256 "cb07cb115c6ad9fe4e9f70ba2e41dae2e4e9d0fb900a9d7b242ddff3b4453388"

        def install
          bin.install "urlencode"
        end
      end
    end
  end
end
